version: 1.0.{build}
image: Visual Studio 2015
branches:
  only:
  - master
configuration: Release
platform: Any CPU
build:
  project: OpenFlareClient.sln
  verbosity: minimal
install:
  git submodule update --init --recursive
before_build:
  - nuget restore